name: citylearn_together
channels:
  - defaults
dependencies:
  - python=3.8.13
  - numpy
  - pip
  - pip:
    - torch==1.12.0
    - torchvision==0.13.0
    - docplex
    - lightgbm==3.3.2
    - scikit-learn==1.0.2
    - pandas
    - citylearn==1.3.6
    - tensorboardX
    - absl-py
    - wandb